### ISSUE TITLE
Non-static instructions

### ISSUE THREAD

**Issue by Jazmusic1234** [nidhigiridhar/cse110-w21-group35#37]
# Task Name 

## Description (1-2 lines)
Sidebar for instructions that pops out when icon is clicked

## Completion Requirements 
* [x] Instructions icon or tab
* [x] Modal pops up when clicked
* [x] Modal retracts when clicked again
