### ISSUE TITLE
Customizable time limits (UI)

### ISSUE THREAD

**Issue by nidhigiridhar** [nidhigiridhar/cse110-w21-group35#59]
# Task Name: Customizable time limits (UI)

## Completion Requirements 
- [ ] Style the form (neutral color so it matches when the color changes between states)
- [ ] make a button with cog logo 
- [ ] when the button is clicked, the form should pop up where the user can enter the time limits.
