### ISSUE TITLE
Progress Bar 

### ISSUE THREAD

**Issue by nidhigiridhar** [nidhigiridhar/cse110-w21-group35#60]
# Task Name 

## Completion Requirements 
- [x] 8 dots (one representing each timer session) at top of the page (make them neutral color so they match when state transitions)
- [x] Each dot changes color (gets darker) from left to right, after a single timer session is completed 
- [x] After a long break is completed, the dots get reset to their original color
